version: "3.9"

services:
  mysql:
    image: mysql:5.7
    platform: ${ARCHITECTURE_PLATFORM}
    volumes:
      - db_data:/var/lib/mysql
      - ./bin/mysql-wp.sh:/usr/local/bin/mysql-wp:rw
    restart: always
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - wordpress-network

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    env_file: .env
    ports:
      - ${PHPMYADMIN_PORT}:80
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./configuration/apache2.conf:/etc/apache2/apache2.conf:ro
    networks:
      - wordpress-network

  wordpress:
    depends_on:
      - mysql
    image: wordpress:latest
    ports:
      - ${WORDPRESS_PORT}:80
    restart: always
    #Fix for windows users on wsl, uncomment if you have a problem with permisssion in wp-admin (install plugin etc.) and rebuild 
    #user: "www-data:1000"
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
      WORDPRESS_DEBUG: ${WORDPRESS_DEBUG:-false}
    volumes:
      - ./wp_data:/var/www/html:rw
      - ./configuration/apache2.conf:/etc/apache2/apache2.conf:ro
      - ./logs/:/var/logs/apache2:ro
    networks:
      - wordpress-network

  wp-cli:
    depends_on:
      - mysql
      - wordpress
    image: wordpress:cli
    working_dir: /var/www/html
    env_file: .env
    # This is required to run wp-cli with the same
    # user-id as wordpress. This way there are no permission problems
    # when running the cli
    #user: xfs
    # Uncomment if you have problem with wp cli path and rebuild
    user: "1000"
    environment:
      WP_CLI_CACHE_DIR: ${WP_CLI_CACHE_DIR}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./wp_data:/var/www/html:rw
      - ./dump:/var/www/html/dump:rw
      - ./bin/install-wp.sh:/usr/local/bin/install-wp:rw
      - ./bin/import-wp.sh:/usr/local/bin/import-wp:rw
    networks:
      - wordpress-network
  aws-cli:
    depends_on:
      - mysql
      - wordpress
    image: vfarcic/aws-cli
    working_dir: /var/www/html
    env_file: .env
    environment:
       - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
       - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
       - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
    #command: sh -c "aws autoscaling describe-auto-scaling-groups | jq -r '.AutoScalingGroups[] | select(.AutoScalingGroupName | startswith(\"${STACK_NAME}-NodeAsg\")).AutoScalingGroupName'"
    # This is required to run wp-cli with the same
    # user-id as wordpress. This way there are no permission problems
    # when running the cli
    # Uncomment if you have problem with wp cli path and rebuild
    #user: "www-data"
    volumes:
      - ./wp_data:/var/www/html:rw
      - ./dump:/var/www/html/dump:rw
      - ./bin/aws-wp.sh:/usr/local/bin/aws-wp:rw
    networks:
      - wordpress-network  
volumes:
  db_data:
  wp_data:

networks:
  wordpress-network:
    driver: bridge
